[build]
  command = "npm run build"
  publish = "dist"

# Force correct MIME types for JavaScript files
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

# Single page app redirect - important!
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200